workflows:
  ios-native-quick-start:
    name: Vixia
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Vixia
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.vivi.vixia
      vars:
        BUNDLE_ID: com.vivi.vixia
        XCODE_WORKSPACE: Vixia.xcworkspace
        XCODE_SCHEME: Vixia
        APP_STORE_APPLE_ID: 6800559995
      xcode: 26.5 # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: pod install
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID" || true)
          LATEST_BUILD_NUMBER=${LATEST_BUILD_NUMBER:-0}
          cd "$CM_BUILD_DIR/Vixia"
          agvtool new-version -all $((LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false
